services:
  rabbitmq-1:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit-1"
    hostname: "rabbit-1"
    environment:
        - RABBITMQ_CONFIG_FILE=${CONFIG_FILE_PATH:-/config/rabbitmq}
        # - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE:?err}
    volumes:
        - ${PWD}/config/rabbit-1/:/config/
        - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
        - rabbits
  rabbitmq-2:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit-2"
    hostname: "rabbit-2"
    environment:
        - RABBITMQ_CONFIG_FILE=${CONFIG_FILE_PATH:-/config/rabbitmq}
        # - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE:?err}
    volumes:
        - ${PWD}/config/rabbit-2/:/config/
        - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
        - rabbits
  rabbitmq-3:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit-3"
    hostname: "rabbit-3"
    environment:
        - RABBITMQ_CONFIG_FILE=${CONFIG_FILE_PATH:-/config/rabbitmq}
        # - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE:?err}
    volumes:
        - ${PWD}/config/rabbit-3/:/config/
        - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
        - rabbits

  haproxy:
    image: haproxy:2.7
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq-1
      - rabbitmq-2
      - rabbitmq-3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge

